### ISSUE TITLE
Та же проблема

### ISSUE THREAD

**Issue by iznv** [AntonPalich/KeyboardIssueExample#1]
Привет. 

Столкнулся с такой же проблемой. Удалось с ней справиться?

Сам решил следующим образом:
- убрал autoresizingMask для inputView,
- выставляю вручную размер inputView так, чтоб соответствовало клавиатуре (достаю из нотификации, когда фрейм клавиатуры меняется).

**Comment by AntonPalich** [comment]
@iznv Привет, да. Вот пример: https://github.com/badoo/Chatto/pull/530 Идея та же, только в дополнение используется UIInputView как контейнер для UIView выставляемой в inputView.

**Comment by iznv** [comment]
@AntonPalich спасибо за ответ.
